chat:
   container_name: chat
   image: tp33/django:1.2
   external_links:
      - mysql:db
   ports:
      - "80:8000"
   volumes:
      - ./:/app
   command: bash -c "chown -R :www-data . && chmod -R 775 . && mod_wsgi-express start-server --reload-on-changes --log-to-terminal ./chatroom/wsgi.py"
